apiVersion: v1
kind: Pod
metadata:
  name: test-list-gpu
spec:
  volumes:
  - name: nvidia-libs-volume
    hostPath: 
      path: /usr/local/nvidia/lib64 
  - name: nvidia-tools-volume
    hostPath: 
      path: /usr/local/nvidia/bin
  containers:
  - name: nvidia-gpu
    image: bootstrapper:5000/zhanghui/tf-gpu-test
    command: [/bin/bash, -c]
    args: [sleep 1d]
    volumeMounts:
      - name: nvidia-libs-volume
        mountPath: /usr/local/nvidia/lib64
        readOnly: true
      - name: nvidia-tools-volume
        mountPath: /usr/local/nvidia/bin
        readOnly: true
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 3
