apiVersion: v1
kind: Pod
metadata:
  name: using-gpu
spec:
  volumes:
  - name: nvidia-libs-volume
    hostPath: 
      path: /usr/local/nvidia/lib64 
  - name: nvidia-tools-volume
    hostPath: 
      path: /usr/local/nvidia/bin
  securityContext:
        runAsUser: 100
  containers:
  - name: nvidia-gpu
    image: bootstrapper:5000/zhanghui/tensorflow-test
    command: [/bin/bash, -c]
    env:
      - name: HOME
        value: /tmp
    args: [sleep 1d]
    volumeMounts:
      - name: nvidia-libs-volume
        mountPath: /usr/local/nvidia/lib64
        readOnly: true
      - name: nvidia-tools-volume
        mountPath: /usr/local/nvidia/bin
        readOnly: true
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 3
